server:
  port: 11003
  servlet:
    context-path: /space-job
spring:
  application:
    name: job
  profiles:
    active: "@profiles.active@"
    group:
      "dev": "dev,db-dev,domain-dev"
task:
  enabled: true